name: Export CFP JSON
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}

      - name: Install deps
        run: pip install pandas feedparser requests

      - name: Generate data.json
        run: python cfp_crawler.py --export-json data.json

      - uses: stefanzweifel/git-auto-commit-action@v5
        with: {commit_message: 'chore(data): update CFP JSON'}

